### PR TITLE
Test v0.8

### PR DESCRIPTION
**Pull request by barche**

### CODE REVIEW

**Comment by ufechner7** [comment]
If we look at the windows tests we see as first error:
```
 Test Summary: | Pass  Total
Doctests: QML |    1      1
   Resolving package versions...
ERROR: empty intersection between QML@0.8.0 and project compatibility 0.7
Stacktrace:
```
Any idea how this can happen (and only on windows-latest, not on ubuntu-latest)?

**Comment by barche** [comment]
On ubuntu-latest the test is actually skipped. The problem was that QmlJuliaExamples still required QML 0.7, but this PR puts QML at version 0.8. This is fixed now.

**Comment by ufechner7** [comment]
@barche Any idea:
```
 ERROR: Error building `ImageMagick`: 
ERROR: LoadError: Unable to open libLLVM!
```

**Comment by barche** [comment]
The ImageMagick error is related to incompatible libtiff versions between GR and ImageMagick. I'm going to leave that as is, it is specific to the many packages required all at once in the examples environment.

**Pull request merged**
