### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ufechner7**
Fix running the examples.

### CODE REVIEW

**Comment by barche** [comment]
What is wrong with the Makie examples? They run for me on Linux, Windows and Mac.

p.s. I gave you access to the repository

**Comment by ufechner7** [comment]
Better now?

**Comment by barche** [comment]
Sorry, I totally misread this last night, I thought this was about running the examples in the CI. `runexamples` is actually intended to be used for CI, so maybe it's better to use uniform instructions based on the readme in the examples: https://github.com/barche/QmlJuliaExamples#qmljuliaexamples ? Maybe extend thos instructions a little to not use a temporary directory?

**Comment by ufechner7** [comment]
I agree, that would be better. On the other hand I think it important the the first example in the README.md file works, and this commit would already fix it.

**Comment by barche** [comment]
I have removed the call to `runexamples` and used LibGit2 instead of the git command, since I'm not sure git will always be in the path. The `runexamples` function is meant for CI and not exported, so I prefer not to mention it at all. Is this OK for you?

**Comment by barche** [comment]
I have removed the call to `runexamples` and used LibGit2 instead of the git command, since I'm not sure git will always be in the path. The `runexamples` function is meant for CI and not exported, so I prefer not to mention it at all. Is this OK for you?

**Comment by ufechner7** [comment]
Perfect!

**Pull request merged**
